# Generated by Django 5.1.2 on 2024-10-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='effort_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marathon_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
