# Generated by Django 5.1.2 on 2024-10-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='notes',
        ),
    ]
